<?php
/**
 * nginx_block_sync.php — sync blocked_ips DB table → nginx geo conf + graceful reload
 *
 * Reads the blocked_ips table, writes /etc/nginx/conf.d/blocked-ips.conf
 * (geo $blocked_ip { ... }), and reloads nginx only when the list changes.
 * The reload uses a wrapper script to avoid giving www-data broad sudo access.
 *
 * ── One-time server setup ────────────────────────────────────────────────────
 *
 *   # Create the conf file owned by www-data so the cron can overwrite it
 *   sudo touch /etc/nginx/conf.d/blocked-ips.conf
 *   sudo chown www-data:www-data /etc/nginx/conf.d/blocked-ips.conf
 *
 *   # Deploy the reload wrapper (scripts/nginx-block-reload.sh → /usr/local/sbin/)
 *   sudo cp /var/www/thameur.org/scripts/nginx-block-reload.sh /usr/local/sbin/nginx-block-reload
 *   sudo chmod 755 /usr/local/sbin/nginx-block-reload
 *   sudo chown root:root /usr/local/sbin/nginx-block-reload
 *
 *   # Allow www-data to run the wrapper as root without a password
 *   echo 'www-data ALL=(root) NOPASSWD: /usr/local/sbin/nginx-block-reload' \
 *     | sudo tee /etc/sudoers.d/www-data-nginx-reload
 *   sudo chmod 440 /etc/sudoers.d/www-data-nginx-reload
 *
 * ── Cron entry ───────────────────────────────────────────────────────────────
 *
 *   * * * * * www-data /usr/bin/php /var/www/thameur.org/cron/nginx_block_sync.php
 *
 * ─────────────────────────────────────────────────────────────────────────────
 */

if (php_sapi_name() !== 'cli') { http_response_code(403); exit; }

define('ADMIN_NO_LOG', true);
require_once __DIR__ . '/../config.php';

define('NGINX_BLOCKED_CONF', '/etc/nginx/conf.d/blocked-ips.conf');
define('NGINX_RELOAD_CMD',   'sudo /usr/local/sbin/nginx-block-reload 2>&1');

$pdo = admin_pdo();
if (!$pdo) { fwrite(STDERR, "[block_sync] DB unavailable\n"); exit(1); }

$rows = $pdo->query(
    "SELECT ip, reason, blocked_at FROM blocked_ips ORDER BY blocked_at ASC"
)->fetchAll();

// ── Build geo block ───────────────────────────────────────────────────────────
$lines   = [];
$lines[] = "# Auto-generated by cron/nginx_block_sync.php — do not edit manually";
$lines[] = "# Entries: " . count($rows);
$lines[] = "geo \$blocked_ip {";
$lines[] = "    default 0;";
foreach ($rows as $r) {
    $ip     = trim($r['ip']);
    if (!filter_var($ip, FILTER_VALIDATE_IP)) continue; // skip corrupt rows
    $reason = preg_replace('/[\x00-\x1f#\n\r]+/', ' ', trim($r['reason'] ?? ''));
    $reason = substr($reason, 0, 80);
    $lines[] = "    $ip/32 1;" . ($reason !== '' ? "  # $reason" : '');
}
$lines[] = "}";

$new = implode("\n", $lines) . "\n";

// ── Compare (strip comment lines before diffing so timestamp doesn't trigger reload) ──
$strip = fn(string $s): string => preg_replace('/^#.*\n?/m', '', $s);
$old   = file_exists(NGINX_BLOCKED_CONF) ? (string)@file_get_contents(NGINX_BLOCKED_CONF) : '';

if ($strip($new) === $strip($old)) {
    exit(0); // list unchanged — no reload needed
}

// ── Write new config ──────────────────────────────────────────────────────────
if (@file_put_contents(NGINX_BLOCKED_CONF, $new) === false) {
    fwrite(STDERR, "[block_sync] Cannot write " . NGINX_BLOCKED_CONF . " — check ownership\n");
    exit(1);
}

// ── Graceful reload (nginx -t first, then reload on pass) ────────────────────
$out    = (string)shell_exec(NGINX_RELOAD_CMD);
$failed = stripos($out, 'failed') !== false || stripos($out, 'error') !== false;

if ($failed) {
    fwrite(STDERR, "[block_sync] Reload failed: $out\n");
    exit(1);
}

echo '[' . gmdate('Y-m-d H:i:s') . " UTC] Synced " . count($rows) . " blocked IPs, nginx reloaded\n";
exit(0);
